### ISSUE TITLE
PlosCompBiol submission guidelines

### ISSUE THREAD

**Issue by tknijnen** [AllenCellModeling/pytorch_integrated_cell#82]
## Issue summary
Listing PlosCompBiol submission guidelines
## Details
Full guidelines:
https://journals.plos.org/ploscompbiol/s/submission-guidelines

## TODO
- [ ] PDF not latex
- [ ] Manuscript text should be double-spaced.
- [ ] Include page numbers and line numbers in the manuscript file
- [ ] Supporting information captions should follow the citations in the main text document.
- [ ] Figure captions are inserted immediately after the first paragraph in which the figure is cited. Figure files are uploaded separately. (It’s fine to leave the figures and tables in the manuscript as well) 
- [ ] Tables are inserted immediately after the first paragraph in which they are cited.
- [ ] Supporting information files are uploaded separately.
- [ ] Have a full title (<200 characters) and a short title (<10 characters)
- [ ] The corresponding author must provide an ORCID iD at the time of submission by entering it in the user profile in the submission system. 
- [ ] Provide at minimum one contribution for each author in the submission system. Use the CRediT taxonomy to describe each contribution. Read the policy and the full list of roles. https://journals.plos.org/ploscompbiol/s/authorship#loc-author-contributions
- [ ] Upload a cover letter as a separate file in the online system. The cover letter should address the following questions: 1) Why is this manuscript suitable for publication in PLOS Computational Biology? 2) Why will your study inspire the other members of your field, and how will it drive research forward?
- [ ] Abstract is limited to 300 words
- [ ] Author summary (150-200 words) seems required.
- [ ] Authors posting on bioRxiv may submit direclty to PLOS journals through bioRxiv’s direct transfer to journal service. https://www.biorxiv.org/submit-a-manuscript
- [ ] Suggest suitable editors and at least four potential reviewers when submitting their manuscript.
- [ ] Is our manuscript a Methods paper? See https://journals.plos.org/ploscompbiol/s/submission-guidelines#loc-methods-submissions
